# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: xl000's blog
email: l_xb@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
    xl000's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xiaobin0860.github.io" # the base hostname & protocol for your site
twitter_username: xiaobin0285
github_username:  xiaobin0860

# Build settings
markdown: kramdown
