# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown
gems: [jekyll-paginate]
highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

exclude: [HelloCocosJs, README.md, otp_doc]

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

title : 乌托邦

author:
  name: xiaobin
  role: xl
  email: xiaobin0860@gmail.com
  github: xiaobin0860
  twitter: 
  facebook: 
  googleplus: 
  bio: "Stay hungry, Stay foolish."
  uno-dbyll: https://xiaobin0860.github.io
